### ISSUE TITLE
Implement Solve Media captcha

### ISSUE THREAD

**Issue by avery000** [spbriggs/recaptcha-plugin#1]
http://wsnippets.com/integrate-solve-media-captcha-php/

**Comment by spbriggs** [comment]
Added in v1.1 beta release

**Comment by avery000** [comment]
Thanks! Where might be the download for that?

**Comment by spbriggs** [comment]
It's on the releases tab : https://github.com/spbriggs/recaptcha-plugin/releases

**Comment by avery000** [comment]
Thankyou very much.

**Comment by avery000** [comment]
umm.. how do i select only solvemedia? I tried leaving blank the recaptcha keys and only having the solvemedia keys but that didn't work.

**Comment by avery000** [comment]
how do i select solvemedia? i deactivated and even deleted the old plugin but the new one still shows as version 1.0 and not as 1.1 beta

**Comment by spbriggs** [comment]
You need to change the function call to spb_recaptcha_add_SolveMedia_Script()

I seem to have messed up the instructions in the readme file but if you look at the sample-public-index.php file it's explained in there.

The version number's not been bumped up yet as this is a beta release.

**Comment by avery000** [comment]
Yay! It works thanks! btw you have an extra (); in your example index.php

**Comment by spbriggs** [comment]
Cool!

Thanks for spotting the typo in the example.

**Comment by avery000** [comment]
Just wondering if you know how to change the site title in index.php, the example one or how to change the background. TIA

**Comment by spbriggs** [comment]
You can set the title like this:

yourls_add_filter( 'html_title', 'set_my_title' );
function set_my_title($input_title)
{
    return "Here's my title";
}

For backgrounds have a look at the random background plugin that comes with Yourls. You should be able to use the code from that.

**Comment by avery000** [comment]
where do i put that?

**Comment by spbriggs** [comment]
Put it in your index.php just after the line:

// Start YOURLS engine
require_once( dirname(**FILE**).'/includes/load-yourls.php' );
