### ISSUE TITLE
Will not validate and the it really gets weird

### ISSUE THREAD

**Issue by jimlunsford** [spbriggs/recaptcha-plugin#2]
I cannot get the recapture to validate then it sends me to another page that says it can't and won't let me even go back to the homepage.

**Comment by spbriggs** [comment]
Hi Jim. Can you give me the URL where you've installed yourls?

**Comment by jimlunsford** [comment]
http://jlink.in/ it's behaving a little differently then what I posted but
still not right.

Regards,

Jim Lunsford

Email - jimlunsford@gmail.com
Mobile/Text - 812-344-7690
Online - http://jimlunsford.com
            http://facebook.com/therealjimlunsford
            http://twitter.com/jimlunsford

**Comment by jimlunsford** [comment]
http://jlink.in/ it's behaving a little differently then what I posted but still not right.

**Comment by spbriggs** [comment]
It looks like your recaptcha is outside of the form element so it's not getting posted back to the server. If you move the closing </form> tag after the  spb_recaptcha_add_Captcha_Script(); command, it should work.

**Comment by jimlunsford** [comment]
I've tried in and out of places inside here:

{

```
    $site = YOURLS_SITE;

    // Display the form
    echo <<<HTML
    <h2>Enter a new URL to shorten</h2>
    <form method="post" action="">
    <p><label>URL: <input type="text" class="text" name="url" value="http://" /></label></p>
    <p><label>Optional custom short URL: $site/<input type="text" class="text" name="keyword" /></label></p>
    <p><label>Optional title: <input type="text" class="text" name="title" /></label></p>
    <p><input type="submit" class="button primary" value="Shorten" /></p>
    </form> 
```

HTML;

}

I can get it to display after HTML; however all I ever get is "Sorry, but you didn't pass the reCaptcha test"

**Comment by spbriggs** [comment]
See the sample-public-index.php file. It should be like this:

```
echo <<<HTML
        <h2>Enter a new URL to shorten</h2>
        <form method="post" action="">
        <p><label>URL: <input type="text" class="text" name="url" value="http://" /></label></p>
        <p><label>Optional custom short URL: $site/<input type="text" class="text" name="keyword" /></label></p>
        <p><label>Optional title: <input type="text" class="text" name="title" /></label></p>
HTML;
        spb_recaptcha_add_Captcha_Script();
        echo <<<HTML
        <p><input type="submit" class="button primary" value="Shorten" /></p>
        </form> 
HTML;
```

It's important to get the echo, <<< and HTML in the right places.

**Comment by jimlunsford** [comment]
Okay, using your sample index file worked. I am very sorry that I did not try it before and you had to waste your time. If you have a donate link somewhere to where I can give you a few dollars for your time I will gladly do it. Thank you!

**Comment by spbriggs** [comment]
No problem Jim. There's a donation link on my personal website if you really want to tip me :) http://www.simonpbriggs.co.uk/
