### ISSUE TITLE
plugin doesn't prevent using index.php?url=...

### ISSUE THREAD

**Issue by Artemiis** [spbriggs/recaptcha-plugin#3]
```
YOURLS version: 1.7.1
PHP version: 5.5.9-1
```

I want to use a public page with recaptcha. works fine, but it's possible to short urls with index.php?url= ...
with this manual it works: http://blog.yourls.org/2015/05/integrating-the-new-google-recaptcha-with-yourls/

can you integrate this to this plugin?

Greetings

**Comment by spbriggs** [comment]
Sorry, I don't understand what you're asking. Could you give me steps to reproduce the problem and a note of how the actual behaviour is different from the expected behaviour? Thanks

**Comment by Artemiis** [comment]
i use your plugin on my public page. That works fine.
if the domain is sho.rt, you can short urls with sho.rt/index.php?url=[place link here] without solving the captcha.
There are bots, they use this. in the tutorial from yourls this is blocked. Would be nice if ypu can add something like this, because a plugin is much more friendly :)

**Comment by spbriggs** [comment]
Thank you. I understand the issue now. Unfortunately I've not been able to reproduce it on a clean install of Yourls with this plugin. I get the "Sorry, but you didn't pass the recaptcha test" error.

Could you share the URL where you have Yourls installed?

**Comment by Artemiis** [comment]
Now it works, i used the tutorial in the link above, i just want to inform :)
I have also done a clean install and i had much spam (20-50 per night). IIt tooked me som hours to get how they can short something.

**Comment by Artemiis** [comment]
if i have the time, i would do a new install tomorrow and test again to provide you a test domain.

**Comment by spbriggs** [comment]
OK. Thanks for the information. I'll close this issue for now but feel free to reopen it or report a new issue if you can reproduce it.

**Comment by Artemiis** [comment]
ok, here's a clean install with these plugins:
check url
recaptcha
api delete

only in combiantion with these plugins it doesnt work right. only with recaptcha it works. Don't know why, perhaps you can help...

test.mols.me (access: test, test)

**Comment by Artemiis** [comment]
@spbriggs i don't know weather you read it ...

**Comment by spbriggs** [comment]
I'm not able to access that server. DNS is not resolving for me

dig test.mols.me

; <<>> DiG 9.8.3-P1 <<>> test.mols.me
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 53967
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 0

;; QUESTION SECTION:
;test.mols.me.          IN  A

;; AUTHORITY SECTION:
mols.me.        1790    IN  SOA dilbert.ns.cloudflare.com. dns.cloudflare.com. 2022335717 10000 2400 604800 3600

;; Query time: 55 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Sun Aug 21 10:26:09 2016
;; MSG SIZE  rcvd: 95

**Comment by Artemiis** [comment]
you don't have ipv6, right?

wait one moment

**Comment by Artemiis** [comment]
Should work now

**Comment by spbriggs** [comment]
Thanks. Have tested it. As doesn't happen when ReCaptcha is installed on its own, and only happens when other plugins are enabled I'm going to say it's one of the other plugins that's causing the problem. If I get any time I might have a closer look but at the moment I think your problem lies elsewhere.

**Comment by Artemiis** [comment]
I think so, yes. Would be nice if you have a look on in future.
If you have the time, i can enable the domain again.
