### ISSUE TITLE
reCaptcha doesn't work?

### ISSUE THREAD

**Issue by clovisd** [spbriggs/recaptcha-plugin#6]
Hi! I've been trying to use the reCaptcha plugin with my empty install of YOURLS without much luck.

I've created a home public-facing page using the code provided on this repo (https://github.com/spbriggs/recaptcha-plugin/blob/master/sample-public-index.php) and it's breaking my form:
See here: https://s.cl6.us/s/axzEl5YoJ7.png

The URL to this is: https://s.cl6.us

The plugin is enabled and configured with the site and private key.

Any help would be appreciated :)

**Comment by spbriggs** [comment]
Hi

Are you able to see the PHP error log? Something's causing it to crash halfway through rendering the page but it's hard to tell what without an error message.
